= My notes on the link:https://www.udacity.com/course/javascript-promises--ud898[Udacity Javascript Promises Course] +
== Uploading to Remote Repository
1. link:https://help.github.com/articles/creating-a-new-repository/ [Create a new repository on GitHub] + 
To avoid errors, do not initialize the new repository with README, license, or *gitignore* files. You can add these files after your project has been pushed to GitHub.
2. Open Terminal
3. Change the current working directory to your local project.
4. Initialize the local directory as a Git repository. 
---
$ git init
---
5. Add the files in your new local repository. This stages them for the first commit.
---
$ git add .
# Adds the files in the local repository and stages them for commit. To unstage a file, use 'git reset HEAD YOUR-FILE'.
---
6. Commit the files that you've staged in your local repository.
---
$ git commit -m "First commit"
# Commits the tracked changes and prepares them to be pushed to a remote repository. To remove this commit and modify the file, use 'git reset --soft HEAD~1' and commit and add the file again.
---
7. At the top of your GitHub repository's Quick Setup page, click  to copy the remote repository URL.
8. In Terminal, link:https://help.github.com/articles/adding-a-remote/ [add the URL for the remote repository] + where the local repository will be pushed. But before that, remove the existing origin and add a new one.
---
$ git remote remove the origin
# Remove the existing origin
$ git remote add origin https://username@github.com/username/js-learning-promises.git
# Add new origin
$ git push origin master
# Push local repository
Password for https://username@github.com/username/js-learning-promises.git
---
8. If there is an error as below, ............
error: src refspec master does not match any.
error: failed to push some refs to 'https://username@github.com/resant18/js-learning-promises.git'
---
$ git show-ref
$ git push origin HEAD:master
---


---
remote add origin https://resant18@github.com/resant18/js-learning-promises.git
---